import React, { useEffect, useState } from "react";

import { BsArrowRight } from "react-icons/bs";
import CoursesCategoryModel from "../../components/UI/model/coursesCategoryModel";
import Image from "next/image";
import { IoIosArrowRoundBack } from "react-icons/io";
import Layout from "../../HOC/Layout/Layout";
import Link from "next/link";
import { RiComputerLine } from "react-icons/ri";
import ToolBar from "../../components/Navigation/Toolbar/ToolBar";
import axios from "../../HOC/Axios/Axios";
import Head from "next/head";
function CourseCategory({ show, setShow }) {
  const [showModel, setShowModel] = useState(true);
  const [data, setData] = React.useState([]);

  let model;
  if (showModel) {
    model = (
      <div className="">
        <div className="text-xl   px-5  py-3 font-openSansSix">
          Course Categories
        </div>
        <div className="px-5 grid md:grid-cols-3 xl:grid-cols-5 gap-5 pb-5">
          {data.map((val, i) => {
            console.log(val);
            let image = `${process.env.NEXT_PUBLIC_FILE}/images/${val.category_img}`;

            return (
              <div
                className=" border-2  h-24 flex items-center hover:border-green-600 border-gray-300  rounded-lg p-2"
                key={i}
              >
                <div
                  className="relative  h-10 w-10
                sm:h-14  sm:w-14  md:h-16 md:w-16 xl:h-20 xl:w-20  mx-auto "
                >
                  <Image
                    src={val.category_img}
                    alt=""
                    width={100}
                    height={100}
                    placeholder="blur"
                    blurDataURL={val.category_img}
                    layout="responsive"
                  />
                </div>
                <div className=" px-2 flex flex-col">
                  <div className=" font-openSansFour leading-5 line-clamp-2  w-32  ">
                    {" "}
                    {val.category_name}
                  </div>
                  <div className="flex items-center gap-3">
                    <div className=" font-openSansThree">
                      {" "}
                      {val.course} courses
                    </div>
                    <div>
                      <BsArrowRight />
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }
  useEffect(() => {
    const fetch = async () => {
      try {
        await axios.get(`/category/withNum`).then((res) => {
          console.warn(res);
          setData(res.data.data);
        });
      } catch (error) {
        console.log(error);
      }
    };
    fetch();
  }, []);
  return (
    <div>
      <Head>
        <title className="">Sikka-i</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      <Layout>
        <div className="bg-gray-50 h-screen">
          <div
            className="col-span-3 sm:col-span-2
           sm:col-start-2  col-start-2 relative  justify-center row-start-1 flex items-center  capitalize font-openSansFour  lg:col-span-5 lg:text-base
         "
          >
            <div className="  hover:text-blue-500 h-20 w-fit cursor-pointer   flex-row  items-center justify-center  ">
              <div className="cursor-pointer text-black">{model}</div>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}

export default CourseCategory;
