import { MdOutlineSupportAgent, MdSettings } from "react-icons/md";
import React, { useState } from "react";

import { AiFillShopping } from "react-icons/ai";
import { BiRupee } from "react-icons/bi";
import Image from "next/image";
import Layout from "../HOC/Layout/Layout";
import Link from "next/link";
import ScrollTo from "react-scroll-into-view";
import image2 from "../public/ppimage.jpg";
import image3 from "../public/imagevector.jpg";
import Head from "next/head";
import WhyToBeInstructor from "../components/PageComponents/BecomeInstructor/WhyToBeInstructor";
import HowToStart from "../components/PageComponents/BecomeInstructor/HowToStart";

function Become_instructor() {
  const [icon, setIcon] = useState(false);
  const [ids, setIds] = useState("");

  const data = [
    {
      id: 1,
      icon1: (
        <MdOutlineSupportAgent className=" w-10 h-10 md:w-14 md:h-14 lg:w-16 lg:h-16  " />
      ),
      title: "built marketing strategies",
      description:
        "Sikka-I helps our gurus to grow themselves in multiple ways. Our gorilla affiliator team is always focused to push your sales. Not only this Sikka-I promotes best courses, gurus on their own. ",
    },

    {
      id: 2,
      icon1: (
        <MdSettings className=" w-10 h-10 md:w-14 md:h-14 lg:w-16 lg:h-16 " />
      ),
      title: "Technical Support",
      description:
        "Sikka-I is always there to help you technically feom creating content  to building courses, making them ready and promoting to market. Sikka-I has its own course development department where you can record your courses for free and leave it rest for Sikka-I. Our technical team will always guide you through the journey  of Sikka-I to be the ultimate Sikkai guru.",
    },
    {
      id: 3,
      icon1: (
        <AiFillShopping className=" w-10 h-10 md:w-14 md:h-14 lg:w-16 lg:h-16  " />
      ),
      title: " biggest passive income platform",
      description:
        " Sikka-I is the biggest and growing platform to generate lifetime passive income. Providing support we guide younto unlock your potential and grow yourself financially free.",
    },
    {
      id: 4,
      icon1: <BiRupee className="w-10 h-10 md:w-14 md:h-14 lg:w-16 lg:h-16 " />,
      title: "awards and recognition",
      description:
        "Sikka-I is always there to cheer you in your success abd guide you through your hard times . We always love to cheer gurus and create best gurus to help our students. We help you to promote your potential and grow fame globally. Our reward plans  are there to motivate you and deliver your best.",
    },
  ];

  const infos = [
    {
      image: image3,
      description1:
        "Go to start now section and fill your personal details and create your own Guru Id. ",
    },
    {
      image: image2,
      description1:
        "Verify your Kyc Asap. Admins will manaually vefify youe Kyc within 72 hours.Thanking you for your patience. ",
    },
    {
      image: image3,
      description1:
        "Go to Guru dashboard and create course and fill the information.",
    },
    {
      image: image2,
      description1:
        " Add sections, upload course and publish them. There will be manual verification for safety, quality contest and  betterment of the platform. We are grateful for your patience.",
    },
  ];
  return (
    <div>
      <Head>
        <title className="">Sikka-i</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      <Layout>
        <div>
          {/* top section {Want to teach courses through our websites online ?} starts */}
          <div className=" grid  grid-cols-12   p-6 sm:p-10">
            <div className=" col-span-12 md:col-span-6  lg:col-start-2 flex  ">
              <div className="flex flex-col justify-center">
                <div className=" sm:text-lg md:text-3xl   lg:text-4xl  lg:full  text-gray-600 font-openSansEight">
                  {" "}
                  An Education System <br /> That{" "}
                  <span className="text-primary">Inspires Creator</span>
                </div>
                <p className="my-4 text-justify leading-relaxed">
                  Sikka-I is an online platform where we connect learners with
                  instructors , earners with business and dreamers with success
                  . We offer best courses at affordable prices for everyone to
                  master the desired skill.
                </p>
                <div className="capitalize  w-fit flex gap-5  mt-8">
                  <Link href="https://instructor.sikkainepal.com" passHref>
                    <a
                      target="_blank"
                      className="text-sm md:text-lg border cursor-pointer px-3 py-2 md:px-5 md:py-3 bg-primary transition-all ease-in-out duration-200 hover:scale-105 rounded-sm outline-none text-white  font-openSansSix"
                    >
                      start now
                    </a>
                  </Link>
                  <ScrollTo
                    selector={"#whysection"}
                    className="border px-3 py-2 text-sm md:text-lg md:px-5 md:py-3 cursor-pointer bg-gray-300 transition-all ease-in-out duration-200 hover:scale-105 rounded-sm outline-none text-gray-800 font-openSansSix"
                  >
                    learn more
                  </ScrollTo>
                </div>
              </div>
            </div>
            <div className="col-span-10 col-start-1 row-start-1 md:row-start-10 md:col-span-6  md:col-start-7 lg:col-start-8">
              <div className="w-full pb-10 sm:pb-0 sm:w-96  lg:w-10/12  ">
                <Image
                  src="/homeImg 1.png"
                  height={100}
                  alt=""
                  width={100}
                  layout="responsive"
                  placeholder="blur"
                  blurDataURL="/homeImg 1.png"
                  quality={100}
                />
              </div>
            </div>
          </div>
          <div id="whysection">
            <WhyToBeInstructor />
          </div>

          <HowToStart />
        </div>
      </Layout>
    </div>
  );
}

export default Become_instructor;
