import { IoIosArrowBack, IoIosArrowForward } from "react-icons/io";
import React, { useEffect, useState } from "react";
import Head from "next/head";
import Layout from "../../../HOC/Layout/Layout";
import { useRouter } from "next/router";
import Ongoing from "../../../components/PageComponents/MyCourses/Ongoing/Ongoing";
import Completed from "../../../components/PageComponents/MyCourses/Completed/Completed";
import Watchlist from "../../../components/PageComponents/MyCourses/Watchlist/Watchlist";
import All from "../../../components/PageComponents/MyCourses/All/All";
import axios from "../../../HOC/Axios/Axios";
function Index({ total_contents, completed_contents }) {
  const [MyCourses, setMyCourses] = useState([]);
  const [Active, setActive] = useState("all");
  const [Navigation, setNavigation] = useState([
    {
      title: "all",
      status: "all",
    },
    {
      title: "ongoing",
      status: "learning",
    },
    {
      title: "completed",
      status: "completed",
    },
  ]);
  const [Status, setStatus] = useState(false);
  const router = useRouter();

  const showAllClickedData = (data) => {
    setActive(data);
  };

  const getCourses = () => {
    axios
      .get(`/enrolled/coursesByStudents/${Active}`)
      .then((res) => {
        if (res.status === 200) {
          console.log(res);
          setMyCourses(res.data.data.reverse());
          // router.push('/myCourses')
        }
        console.log(res);
      })
      .catch((err) => console.log(err));
  };

  useEffect(() => {
    getCourses();
  }, []);

  let mod;
  switch (Active) {
    case "all":
      mod = <All Acitvated={Active} />;
      break;
    case "learning":
      mod = <Ongoing Acitvated={Active} />;
      break;
    case "completed":
      mod = <Completed Acitvated={Active} />;
      break;
    case "watchList":
      mod = <Watchlist />;
      break;

    default:
      mod = (
        <h1>{`please check your render method in Home.jsx switch case`}</h1>
      );
      break;
  }
  console.log(Active);
  return (
    <div>
      <Head>
        <title className="">Sikka-i</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-16x16.png" />
      </Head>
      <Layout>
        <div className="bg-grayOne px-8 xl:px-16">
          <div>
            <div className="font-openSansSeven text-xl py-8">My Courses</div>
            <div className="flex flex-col md:flex-row justify-between ">
              <div
                className=" w-full md:w-9/12 
            lg:w-6/12 xl:w-5/12 grid grid-cols-4 gap-2 
            place-content-center "
              >
                {Navigation.map((val, i) => {
                  return (
                    <div
                      onClick={() => showAllClickedData(val.status)}
                      key={i}
                      className={`cursor-pointer flex items-center  
                    justify-center  space-x-1 font-openSansFour
                     h-9 ${
                       Active === val.status
                         ? "btn-outline-primary   rounded-3xl"
                         : "w-full"
                     }  capitalize text-sm md:text-base`}
                    >
                      <div className="">{val.title}</div>
                      {val.data ? (
                        <div
                          className={`${i !== 3 ? "bg-secondary" : "bg-gray"}
                        text-white w-4 h-4  text-xs
                         flex justify-center items-center rounded-full`}
                        >
                          {val.data}
                        </div>
                      ) : (
                        ""
                      )}
                    </div>
                  );
                })}
              </div>
              <div
                className=" flex-1  
              
              flex ml-1 flex-row pt-4 md:ml-0 md:pt-0 md:justify-end text-lg items-center
             font-openSansSix"
              >
                <IoIosArrowBack />
                <span className="text-primary">1</span>/12 <IoIosArrowForward />
              </div>
            </div>
          </div>
          {mod}
        </div>
      </Layout>
    </div>
  );
}

export default Index;
